// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWuQEkkPF3PsUUwZEfWqPHAMwFDncHmPg',
    appId: '1:79956562740:android:2898e0006aeaee173b0b61',
    messagingSenderId: '79956562740',
    projectId: 'soil-app-mobile',
    databaseURL: 'https://soil-app-mobile-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soil-app-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaIn4Fe6TeIclewNLWP4kQlo-4ajk48-k',
    appId: '1:79956562740:ios:44e0056f7b0074d23b0b61',
    messagingSenderId: '79956562740',
    projectId: 'soil-app-mobile',
    databaseURL: 'https://soil-app-mobile-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soil-app-mobile.appspot.com',
    iosBundleId: 'com.example.soilClient',
  );
}
